### PR TITLE
Fixed Sequence unit tests

### PR DESCRIPTION
**Pull request by paynemiller92**
### Overview

I noticed the Sequence unit tests were broken and commented out, so I fixed the compile errors and altered the test CSV file to meet what the unit tests expected. Obviously, I don't have a whole lot of domain knowledge for Quizatron, so if you have suggesstions for test data, please let me know!

Check out [the issue](https://github.com/2DSharp/Quizatron/issues/3) for more info!

### Summary of Changes

1. Added sequence test file
2. Uncommented tests.
3. Added needed testing dependency.

### CODE REVIEW

**Comment by 2DSharp** [comment]
Hi, thanks for your efforts. I had to meet the deadlines of a project and had to remove the tests, although this was supposed to be a full TDD-based project at the beginning. Your PR looks good, although I'd like to suggest a change. We probably don't need to do the `fetchFileTest()`, `fetchIntroTest()` and `fetchType()` tests seperately, as they are just testing different column for the CSV. Putting them in a single generic test with three asserts might be a good option.

As for Quizatron, it's a quiz show console application. It's meant to work on live Quiz shows which would be responsible for the display screen's (usually a projected display or LED screen) output. For example: questions will be displayed with different kinds (for example: rapid fire rounds, audio-visual questions etc.). This also has an inbuilt media player to play any kind of audio/video during the course of the quiz.

**Comment by 2DSharp** [comment]
You might wanna check out `SequenceServiceTest` which is dependent on the `SequenceMapper` and the entity of `Sequence`, which is commented out as well.

**Comment by paynemiller92** [comment]
@2DSharp I'll take a look at the other test class, and i'll refactor the existing tests.

**Comment by paynemiller92** [comment]
@2DSharp I have taking a look at `SequenceServiceTest`, and I know the fix, but it's a bit of work. Can you accept this PR and I will submit another one for the sequence service tests?

**Comment by 2DSharp** [comment]
@paynemiller92 Yea, it's a better idea if `SequenceServiceTest` is fixed in a different PR. If you could fix the merge the `fetchFileTest()`, `fetchIntroTest()` and `fetchType()` tests together, it looks good to be merged. :)

**Comment by paynemiller92** [comment]
@2DSharp tests merged!

**Comment by paynemiller92** [comment]
@2DSharp you got it man! I'd be happy too.

**Pull request merged**
