### PR TITLE
Using jackson instead of object streams to serialize and deserialize …

### PR DESCRIPTION
**Pull request by skylerwlewis**
…objects

### CODE REVIEW

**Comment by skylerwlewis** [comment]
Hi there! I thought using Jackson to serialize and deserialize using JSON would be better than the native serialization. However, I was not able to load the sample quizatron.json as a configuration file and start a quiz successfully. Any idea how I might make sure this thing is working as expected? Thanks!

**Comment by 2DSharp** [comment]
Hi. Sorry for the problem. There's not enough documentation around about this.

This is what a sample quizatron.json looks like:

```
{
  "name" : "Inquizzitive 15",
  "alias" : "IQ 15",
  "description" : "An quizzing event in Agartala that held its ground for 15 years.",
  "organizer" : "Ramakrishna Mission Alumni Association",
  "sequence" : "config/sequence.csv",

  "appearance" : {
    "logo" : "img/logo.png",
    "logo-animated" : "img/logo.gif",
    "secondary-animation" : "media/sec-anim.mp4",
    "theme-music" : "media/theme.mp3",
    "default-background" : "img/bg.jpg",
    "theme-left-bg" : "img/sidebars/main.jpg",
    "theme-color" : "#44C7F2",
    "theme-bg-color" : "#23222F",
    "text-color" : "#DADAF6"
  }
}
```

**Comment by 2DSharp** [comment]
I like your approach towards serialization using Jackson. This could be a better alternative. 

As you can see, this project is using Google GSON to process json files. Maybe make it consistent to use the same library for JSON files? Could be either gson or jackson.

Thoughts?

**Comment by hexmind** [comment]
This PR duplicates https://github.com/2DSharp/Quizatron/pull/8

**Pull request closed without merging**
